# Generated by Django 3.2.9 on 2021-11-05 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='milleage',
            new_name='mileage',
        ),
    ]
